### PR TITLE
Create README-ja.md

### PR DESCRIPTION
**Pull request by t-cool**
Hi. 

I'd like to made the Japanese version of this quickstart tutorial so that Japanese newbies can start ClojureScript programing on shadow-cljs at once.

I'll keep on updating the Japanese version every time you update README.md .

### CODE REVIEW

**Comment by thheller** [comment]
Hey, this is great. Thank you.

Although in the long run it might make more sense to do a completely separate repo which I'll happily link to from the shadow-cljs README. May you'll want to translate the comments in the `shadow-cljs.edn` or source files as well at some point.

**Comment by t-cool** [comment]
@thheller 

Thank you for merging the Japanese README.

By the way, would it be possible to translate Shadow CLJS User's Guide into Japanese?

I've translated ClojureScript book into Japanese before 
[https://github.com/t-cool/clojurescript-unraveled](https://github.com/t-cool/clojurescript-unraveled
) 

It would be happy if you gave me a chance to translate into Japanese. 

If it's okay, I'll fork the repository of shadow-cljs.github.io and comment out the original English texts and generate Japanese version of the website using asciidoc.

**Comment by thheller** [comment]
Yes, it is absolutely OK to fork and translate the docs. Unfortunately I cannot help or verify the result but I'll happily add links to the fork from the english sources/repos.

**Comment by t-cool** [comment]
@thheller 
Thank you for giving me a chance!
I'll make Japanese version and deploy the site to GitHub Pages.
I'll ask some Japanese Clojurian to check the translation too.

**Pull request merged**
